# Generated by Django 5.0.3 on 2024-03-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
