# Generated by Django 5.0.3 on 2024-03-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_event_rename_author_article_author_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='event_images/%Y/%m/%d'),
        ),
    ]
